### ISSUE TITLE
FPEs in ACE tests 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#528]
Looks like the ACE tests are failing on a number of platforms including proxima due to FPEs, see http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=5039598&build=90138 .  It started yesterday.  When I do a backtrace in gdb, it is not superhelpful.  Here it is: 

```
 at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Kokkos_Parallel.hpp:191
#12 0x00007fffede73c89 in LCM::ParallelConstitutiveModel<PHAL::AlbanyTraits::Jacobian, PHAL::AlbanyTraits, LCM::ACEiceMiniKernel<PHAL::AlbanyTraits::Jacobian, PHAL::AlbanyTraits> >::computeState(PHAL::Workset&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Teuchos::RCP<PHX::MDField<Sacado::Fad::DFad<double> const> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Teuchos::RCP<PHX--Type <RET> for more, q to quit, c to continue without paging--

::MDField<Sacado::Fad::DFad<double> const> > > > >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Teuchos::RCP<PHX::MDField<Sacado::Fad::DFad<double>> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Teuchos::RCP<PHX::MDField<Sacado::Fad::DFad<double>> > > > >) (this=0x7af200, workset=..., dep_fields=std::map with 8 elements = {...}, 
    eval_fields=std::map with 14 elements = {...})
    at /home/ikalash/nightlyCDash/repos/Albany/src/./LCM/parallel_models/ParallelConstitutiveModel_Def.hpp:61
#13 0x00007fffedfd939c in LCM::ConstitutiveModelInterface<PHAL::AlbanyTraits::Jacobian, PHAL::AlbanyTraits>::evaluateFields (this=0x7aed50, 
    workset=...) at /home/ikalash/nightlyCDash/repos/Albany/src/LCM/models/ConstitutiveModelInterface_Def.hpp:242
#14 0x00007ffff6cce9f0 in PHX::DagManager<PHAL::AlbanyTraits>::evaluateFields (this=0x752268, d=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Phalanx_DAG_Manager_Def.hpp:450
#15 0x00007ffff6ccb2d9 in PHX::EvaluationContainer<PHAL::AlbanyTraits::Jacobian, PHAL::AlbanyTraits>::evaluateFields (this=0x752260, d=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Phalanx_EvaluationContainer_Def.hpp:216
#16 0x00007ffff6c7565a in PHX::FieldManager<PHAL::AlbanyTraits>::evaluateFields<PHAL::AlbanyTraits::Jacobian> (this=0x752180, d=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Phalanx_FieldManager_Def.hpp:310
#17 0x00007ffff6c5c608 in Albany::Application::computeGlobalJacobianImpl (this=0x721f20, alpha=0, beta=1, omega=0, current_time=0, x=..., 
    xdot=..., xdotdot=..., p=..., f=..., jac=..., dt=0) at /home/ikalash/nightlyCDash/repos/Albany/src/Albany_Application.cpp:1491
#18 0x00007ffff6c5d52f in Albany::Application::computeGlobalJacobian (this=0x721f20, alpha=0, beta=1, omega=0, current_time=0, x=..., xdot=..., 
    xdotdot=..., p=..., f=..., jac=..., dt=0) at /home/ikalash/nightlyCDash/repos/Albany/src/Albany_Application.cpp:1629
#19 0x00007ffff6cf000b in Albany::ModelEvaluator::evalModelImpl (this=0x9128b0, inArgs=..., outArgs=...)
    at /home/ikalash/nightlyCDash/repos/Albany/src/Albany_ModelEvaluator.cpp:768
#20 0x00007ffff6b9333e in Thyra::ModelEvaluatorDefaultBase<double>::evalModel (this=0x9128b0, inArgs=..., outArgs=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Thyra_ModelEvaluatorDefaultBase.hpp:691
#21 0x00007ffff6bb24e5 in Thyra::DefaultModelEvaluatorWithSolveFactory<double>::evalModelImpl (this=0xa11180, inArgs=..., outArgs=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Thyra_DefaultModelEvaluatorWithSolveFactory.hpp:325
#22 0x00007ffff6b9333e in Thyra::ModelEvaluatorDefaultBase<double>::evalModel (this=0xa111c8, inArgs=..., outArgs=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Thyra_ModelEvaluatorDefaultBase.hpp:691
#23 0x00007fffe4380e48 in LOCA::Thyra::Group::computeJacobian (this=0x9b5cc0)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src-loca/src-thyra/LOCA_Thyra_Group.C:180
#24 0x00007fffe3d5dbb8 in LOCA::MultiContinuation::ConstrainedGroup::computeJacobian (this=0xa9ee30)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src-loca/src/LOCA_MultiContinuation_ConstrainedGroup.C:357
#25 0x00007fffe3d6b335 in LOCA::MultiContinuation::ExtendedGroup::computeJacobian (this=0xa8f3e8)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src-loca/src/LOCA_MultiContinuation_ExtendedGroup.C:135
#26 0x00007fffe37ac797 in NOX::Direction::Newton::compute (this=0xb66750, dir=..., soln=..., solver=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src/NOX_Direction_Newton.C:131
--Type <RET> for more, q to quit, c to continue without paging--
#27 0x00007fffe37a1ade in NOX::Direction::Generic::compute (this=0xb66750, d=..., g=..., s=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src/NOX_Direction_Generic.C:59
#28 0x00007fffe37acdee in NOX::Direction::Newton::compute (this=0xb66750, dir=..., soln=..., solver=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src/NOX_Direction_Newton.C:164
#29 0x00007fffe37df470 in NOX::Solver::LineSearchBased::step (this=0x95c840)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src/NOX_Solver_LineSearchBased.C:194
#30 0x00007fffe37dfa84 in NOX::Solver::LineSearchBased::solve (this=0x95c840)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src/NOX_Solver_LineSearchBased.C:260
#31 0x00007fffe3e93a38 in LOCA::Stepper::compute (this=0x9708c0)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src-loca/src/LOCA_Stepper.C:600
#32 0x00007fffe3d17039 in LOCA::Abstract::Iterator::iterate (this=0x9708c0)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src-loca/src/LOCA_Abstract_Iterator.C:150
#33 0x00007fffe3d16f80 in LOCA::Abstract::Iterator::run (this=0x9708c0)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/nox/src-loca/src/LOCA_Abstract_Iterator.C:128
#34 0x00007fffeb2cd413 in Piro::LOCASolver<double>::evalModelImpl (this=0x9d9b80, inArgs=..., outArgs=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/piro/src/Piro_LOCASolver_Def.hpp:197
#35 0x00007ffff6b9333e in Thyra::ModelEvaluatorDefaultBase<double>::evalModel (this=0x9d9d10, inArgs=..., outArgs=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Thyra_ModelEvaluatorDefaultBase.hpp:691
#36 0x000000000047b7d3 in Piro::Detail::PerformSolveImpl<double, Thyra::VectorBase<double> const, Thyra::MultiVectorBase<double> const> (
    model=..., computeResponses=..., computeSensitivities=false, responses=..., sensitivities=..., observer=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Piro_PerformSolve_Def.hpp:120
#37 0x0000000000477978 in Piro::Detail::PerformSolveImpl<double, Thyra::VectorBase<double> const, Thyra::MultiVectorBase<double> const> (
    model=..., solveParams=..., responses=..., sensitivities=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Piro_PerformSolve_Def.hpp:162
#38 0x0000000000474642 in Piro::PerformSolveBase<double> (piroModel=..., solveParams=..., responses=..., sensitivities=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Piro_PerformSolve_Def.hpp:291
#39 0x0000000000470998 in Piro::PerformSolve<double> (piroModel=..., solveParams=..., responses=..., sensitivities=...)
    at /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build-debug/install/include/Piro_PerformSolve_Def.hpp:230
#40 0x000000000046106f in main (argc=2, argv=0x7fffffffd0b8) at /home/ikalash/nightlyCDash/repos/Albany/src/Main_Solve.cpp:144
```
Here are the last lines in Albany from the stack: 

https://github.com/SNLComputation/Albany/blob/master/src/LCM/parallel_models/ParallelConstitutiveModel_Def.hpp#L61-L67

I was surprised to see Kokkos::parallel_fors...  I thought that was all removed from LCM awhile ago? 

@lxmota, can you please look at this?  I think your changes yesterday broke the tests.

**Comment by lxmota** [comment]
@ikalash Newer material models are all based on the parallel kernel work that Nic did for us. What was removed was all the ad-hoc Kokkos code for some of the material models.

Anyhow, there was a Sacado type mismatch that I hopefully fixed now.

**Comment by ikalash** [comment]
Thanks @lxmota.  I will check the nightlies tomorrow and close the issue if it is resolved.

**Comment by ikalash** [comment]
I can confirm that the issue has been resolved.
