### ISSUE TITLE
Discretization_Parallel_Unit_Test timing out in Blake gcc warning-free build

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#706]
https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1279413&build=18992 

@kliegeois is looking into it.

**Comment by kliegeois** [comment]
Quick update: I found the issue but not yet how to solve it:

```
#0  __cxxabiv1::__cxa_throw (obj=0xaba1a0,
    tinfo=0x7ea350 <_ZTISt13runtime_error@@GLIBCXX_3.4>,
    dest=0x4fec40 <_ZNSt13runtime_errorD1Ev@plt>)
    at ../../.././libstdc++-v3/libsupc++/eh_throw.cc:75
#1  0x00007fffd4955c25 in Tpetra::MultiVector<long long, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::unpackAndCombine (this=0xabe830, importLIDs=..., imports=..., constantNumPackets=0,
    CM=Tpetra::ABSMAX)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:1685
#2  0x00007fffd4f69653 in Tpetra::DistObject<long long, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doTransferNew (this=0xabe830, src=..., CM=Tpetra::ABSMAX, numSameIDs=45,
    permuteToLIDs=..., permuteFromLIDs=..., remoteLIDs=..., exportLIDs=...,
    distor=...,
    revOp=Tpetra::DistObject<long long, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DoForward,
    commOnHost=true, restrictedMode=false)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/tpetra/core/src/Tpetra_DistObject_def.hpp:1222
#3  0x00007fffd4f65b7d in Tpetra::DistObject<long long, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doTransfer---Type <return> to continue, or q <return> to quit---

 (this=0xabe830, src=..., transfer=...,
    modeString=0x7fffffff2ba0 "doExport (forward mode)",
    revOp=Tpetra::DistObject<long long, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DoForward,
    CM=Tpetra::ABSMAX, restrictedMode=false)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/tpetra/core/src/Tpetra_DistObject_def.hpp:555
#4  0x00007fffd4f63155 in Tpetra::DistObject<long long, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doExport
    (this=0xabe830, source=..., exporter=..., CM=Tpetra::ABSMAX,
    restrictedMode=false)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/tpetra/core/src/Tpetra_DistObject_def.hpp:328
#5  0x00007ffff338ed7f in panzer::DOFManager::buildGlobalUnknowns_GUN (
    this=0xa9c190, tagged_overlap_mv=..., overlap_mv=...)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp:749
#6  0x00007ffff338c8a3 in panzer::DOFManager::buildGlobalUnknowns (
    this=0xa9c190, geomPattern=...)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp:487
#7  0x00007ffff333bc6a in panzer::BlockedDOFManager::buildGlobalUnknowns (
    this=0xaa18c0, indexer=..., geomPattern=...)
---Type <return> to continue, or q <return> to quit---    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/panzer/dof-mgr/src/Panzer_BlockedDOFManager.cpp:781
#8  0x00007ffff333df69 in panzer::BlockedDOFManager::buildGlobalUnknowns (
    this=0xaa18c0, geomPattern=...)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/panzer/dof-mgr/src/Panzer_BlockedDOFManager.cpp:1054
#9  0x00007ffff333e44b in panzer::BlockedDOFManager::buildGlobalUnknowns (
    this=0xaa18c0)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/panzer/dof-mgr/src/Panzer_BlockedDOFManager.cpp:1099
#10 0x00007ffff656e97b in Albany::BlockedSTKDiscretization::BlockedSTKDiscretization (this=0xa98c60, discParams_=..., stkMeshStruct_=..., comm_=...,
    rigidBodyModes_=..., sideSetEquations_=...)
    at /ascldap/users/knliege/dev/albany_all/blake/Albany/src/disc/stk/Albany_BlockedSTKDiscretization.cpp:351
#11 0x000000000050aaf1 in Albany::AlbanyBlockedDOFManager_BlockedSTKDiscretizationTests_assortedTests_UnitTest::runUnitTestImpl (
    this=0x7ebfa0 <Albany::instance_AlbanyBlockedDOFManager_BlockedSTKDiscretizationTests_assortedTests_UnitTest>, out=..., success=@0x7fffffff7fff: true)
    at /ascldap/users/knliege/dev/albany_all/blake/Albany/tests/unit/disc/UnitTest_BlockedDOFManager.cpp:382
#12 0x00007fffcc468398 in Teuchos::UnitTestBase::runUnitTest (
    this=0x7ebfa0 <Albany::instance_AlbanyBlockedDOFManager_BlockedSTKDiscretiza---Type <return> to continue, or q <return> to quit---
tionTests_assortedTests_UnitTest>, out=...)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestBase.cpp:62
#13 0x00007fffcc46da13 in Teuchos::UnitTestRepository::runUnitTestImpl (
    unitTest=..., out=...)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestRepository.cpp:539
#14 0x00007fffcc46c28a in Teuchos::UnitTestRepository::runUnitTests (out=...)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestRepository.cpp:317
#15 0x00007fffcc46d39f in Teuchos::UnitTestRepository::runUnitTestsFromMain (
    argc=1, argv=0x7fffffff8e28)
    at /ascldap/users/knliege/dev/trilinos_all/Trilinos_Albany/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestRepository.cpp:423
#16 0x00000000005a04bb in main (argc=1, argv=0x7fffffff8e28)
    at /ascldap/users/knliege/dev/albany_all/blake/Albany/tests/unit/Albany_UnitTestMain.cpp:28
```

It seems that `constantNumPackets==0` at line 1222 of Tpetra_DistObject_def.hpp.

**Comment by kliegeois** [comment]
@ikalash I just pushed a commit to master to disable the use of serial mesh for that unit test. I tested it on Blake, it worked fine.
